name: Build BoosterApp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: Build the EXE and log output
        run: |
          pyinstaller --onefile --windowed --icon=ak_icon.ico Booster.py > log.txt 2>&1 || exit 1

      - name: Upload logs if build failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: log.txt
