name: Build BoosterApp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyqt5

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=ak_icon.ico Booster.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BoosterApp
        path: dist/Booster.exe
